spring.application.name=p2-revpay

#database configuration
spring.datasource.url=jdbc:oracle:thin:@localhost:1522/freepdb1
spring.datasource.username=classuser
spring.datasource.password=class_practice

#hibernate configuration
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true