spring.application.name=p2-revpay

#database configuration
spring.datasource.url=jdbc:oracle:thin:@localhost:1522/freepdb1
spring.datasource.username=p2_revpay
spring.datasource.password=revpay_p2

#hibernate configuration
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true